### PR TITLE
Fixed epoch date decoding being affected by the local time zone

### LINKED ISSUE #209: Failing unit-test
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### cbor2 version

5.6.0

### Python version

3.11.5

### What happened?

I ran `python -m pytest -sv tests/` and one of the date tests failed:

```
tests/test_decoder.py:389: in test_date
    assert decoded == expected
E   assert datetime.date(2018, 12, 30) == datetime.date(2018, 12, 31)
```

### How can we reproduce the bug?

run `python -m pytest -sv tests/test_decoder.py`

### PR DESCRIPTION
**Pull request by agronholm**
Fixes #209.

### CODE REVIEW

File: source/module.c [hunk 1]
```diff
@@ -1000,6 +1003,9 @@ PyInit__cbor2(void)
 
 #undef INTERN_STRING
 
+    if (!_CBOR2_date_ordinal_offset &&
+            !(_CBOR2_date_ordinal_offset = PyLong_FromLong(719163)))
```
Comment (meejah) [inline source/module.c:1007]: Would be helpful (to me, who doesn't know CBOR expect as a user) to know what this magic number means.

Comment (agronholm) [reply source/module.c:1007]: See the CBOR definition for [semantic tag 100](https://datatracker.ietf.org/doc/html/draft-ietf-cbor-date-tag-04#section-2.1). 719163 is the number of days between the minimum supported CBOR date and the [minimum supported Python date ordinal](https://docs.python.org/3/library/datetime.html#datetime.date.fromordinal) (which starts from January 1 of year 1).

**Comment by agronholm** [comment]
Turns out the call was faulty and caused the C extension to fail compilation.
